# Generated by Django 4.0.4 on 2022-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='interyer',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
