# Generated by Django 4.0.4 on 2022-12-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_youtube'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Youtube',
            new_name='Link',
        ),
    ]
