# Generated by Django 4.0.4 on 2023-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='img5',
        ),
        migrations.AddField(
            model_name='tovar',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
